version: "3.9"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  tts-server:
    build:
      context: .
      dockerfile: Dockerfile.tts
    container_name: tts-server
    ports:
      - "5003:5003"
    restart: unless-stopped

  interview-app:
    build: .
    container_name: interview-mentor
    ports:
      - "5002:5002"
    volumes:
      - ./db:/app/db
    depends_on:
      - ollama
      - tts-server
    environment:
      - OLLAMA_URL=http://ollama:11434/api/chat
      - OLLAMA_TAGS=http://ollama:11434/api/tags
      - TTS_SERVER=http://tts-server:5003/tts
    restart: unless-stopped

volumes:
  ollama_data:
